#                            -*- mode: org; -*-
#
#+TITLE:             OpenFOAM README for version 2.1.0
#+AUTHOR:               The OpenFOAM Foundation
#+DATE:                     19th December 2011
#+LINK:                  http://www.openfoam.org
#+OPTIONS: author:nil ^:{}
# Copyright (c) 2011 OpenFOAM Foundation.

* About OpenFOAM
  OpenFOAM is a free, open source computational fluid dynamcis (CFD) software
  package released by the OpenFOAM Foundation. It has a large user base across
  most areas of engineering and science, from both commercial and academic
  organisations. OpenFOAM has an extensive range of features to solve anything
  from complex fluid flows involving chemical reactions, turbulence and heat
  transfer, to solid dynamics and electro-magnetics.

* Copyright
  OpenFOAM is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  See the file =COPYING= in this directory or
  [[http://www.gnu.org/licenses/]], for a description of the GNU General Public
  License terms under which you can copy the files.

* Do Not Use This Software for Anything
  I have removed the Docs and Support to the OpenFOAM website because if you 
  need support, you need to go download OpenFOAM from their website.

* What I am doing
  I am currently shifting the 2.1 release to windows using the symscape patch 
  to run it in Visual Studio. Most of the alterations are #includes and 
  forward declarations. There is no other build system, I am manually adding
  the #includes to each file that needs them. I have a python script that 
  should be up here soon that I use to fix the case sensitivity issues.
